version: "3.8"
services:
  nginx:
    image: nginx:1.21.1
    networks:
      - nginx-django
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - static:/data/static
      - media:/data/media
    ports:
      - 80:80
  
  mariadb:
    image: mariadb:10.5
    networks:
      - nginx-django
    volumes:
      - /home/ubuntu/database:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
    
  djangoapi:
    build:
        context: .
        dockerfile: ./server.Dockerfile
    networks:
        - nginx-django
    volumes:
        - ${PWD}:/home/ubuntu/MyAPI
        - media:/home/ubuntu/MyAPI/media
        - static:/home/ubuntu/MyAPI/static
    depends_on: 
        - mariadb


networks:
  nginx-django:

volumes:
  static:
  media:

secrets:
  MARIADB_ROOT_PASSWORD:
    external: true