version: "3.8"
services:
  nginx:
    image: nginx:1.21.0
    networks:
      - nginx-django
    volumes:
      - /home/ubuntu/MyAPI/nginx.conf:/etc/nginx/nginx.conf
      - static:/data/static
      - media:/data/media
    ports:
      - 80:80
  djangoapi:
    build: 
        context: .
        dockerfile: ./server.Dockerfile
    networks:
      - nginx-django
    volumes:
      - ${PWD}:/home/ubuntu/MyAPI
      - media:/home/ubuntu/MyAPI/media
      - static:/home/ubuntu/MyAPI/static
  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - /home/ubuntu/database:/var/lib/mysql
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER: root
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD


networks:
  network:

volumes:
  static-volume:
  media-volume:
    

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true