# Generated by Django 3.2.5 on 2021-07-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
